/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_automotive_ai_phonon_rtc_AudioProcessJni */

extern "C"
JNIEXPORT jint JNICALL Java_com_example_myassistantdemo_rtc_AudioProcessJni_initiateNSInstance(JNIEnv *env, jclass clazz, jlong sf, jint mode) {
    // TODO: implement initiateNSInstance()
}
JNIEXPORT jint JNICALL Java_com_example_myassistantdemo_rtc_AudioProcessJni_processNS32K(JNIEnv *env, jclass clazz, jobject buffer1, jshortArray outframe, jint sf) {
    // TODO: implement processNS32K()
}
JNIEXPORT jint JNICALL Java_com_example_myassistantdemo_rtc_AudioProcessJni_processNS(JNIEnv *env, jclass clazz, jobject buffer1, jshortArray outframe, jint sf) {
    // TODO: implement processNS()
}
JNIEXPORT void JNICALL Java_com_example_myassistantdemo_rtc_AudioProcessJni_NSProcess(JNIEnv *env, jclass clazz, jint sf) {
// TODO: implement NSProcess()
}
JNIEXPORT jint JNICALL Java_com_example_myassistantdemo_rtc_AudioProcessJni_destoryNS(JNIEnv *env, jclass clazz) {
// TODO: implement destoryNS()
}

JNIEXPORT void JNICALL Java_com_example_myassistantdemo_rtc_AudioProcessJni_AgcFree(JNIEnv *env, jclass clazz) {
// TODO: implement AgcFree()
}

JNIEXPORT jint JNICALL Java_com_example_myassistantdemo_rtc_AudioProcessJni_AgcFun(JNIEnv *env, jclass clazz, jobject buffer1,
        jshortArray s_arr, jint frame_size) {
// TODO: implement AgcFun()
}

JNIEXPORT jlong JNICALL Java_com_example_myassistantdemo_rtc_AudioProcessJni_AgcInit(JNIEnv *env, jclass clazz, jlong min_level,
        jlong max_level, jlong fs) {
// TODO: implement AgcInit()
}

JNIEXPORT void JNICALL Java_com_example_myassistantdemo_rtc_AudioProcessJni_AgcProcess(JNIEnv *env, jclass clazz) {
// TODO: implement AgcProcess()
}
